apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elysia-api
  labels:
    app.kubernetes.io/name: elysia-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: elysia-api
    app.kubernetes.io/instance: {{ .Release.Name }}
