# Default values for elysia-api
# This is a YAML-formatted file.

image:
  repository: ghcr.io/lukew-cogapp/elysia-api
  tag: main
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-creds

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: elysia-api.localhost
  path: /
