image:
  repository: elysia-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  host: elysia-api.localhost
  path: /
