# Default values for elysia-api
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

image:
  repository: elysia-api
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: elysia-api.localhost
  path: /
